### ISSUE TITLE
Show error on duplicate payment

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments-ui#136] opened 2015-06-30 16:42 UTC
Related to the work @kumar303 did on showing an error, currently a duplicate payment shows an error:

```
payments_service.braintree.views:INFO buyer 4 is already subscribed to product 3 :/srv/payments-service/payments_service/braintree/views.py:82
[30/Jun/2015 16:42:09]"POST /api/braintree/subscriptions/ HTTP/1.0" 400 111
```

And the UI just spins.

**Comment by muffinresearch** [comment] 2015-07-01 09:49
Duplicate of #92

**Closed** 2015-07-01 09:50 UTC
Labels: duplicate
